version: "3.8"

services:
  ethereum-node:
    image: "karyonfood/besu-peer"
    restart: always
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  ethstats-client:
    image: "karyonfood/ethstats-client"
    restart: always
    depends_on:
      - "ethereum-node"
    command:
      [
        "./scripts/wait-for-it.sh",
        "ethereum-node:8545",
        "--",
        "npm",
        "run",
        "start",
      ]
    environment:
      INSTANCE_NAME: "node" #Add your instance name here
      WS_SECRET: "&6s61thEYAY9upDOgVihSAeGu!D!rP"
      WS_SERVER: "https://stats.karyon.karyonfood.com"
      RPC_HOST: "ethereum-node"
